function q(g,f,k,i,d){function s(c,a){c.beginPath();c.moveTo(a.a[0].x,a.a[0].y);c.lineTo(a.a[1].x,a.a[1].y);c.lineTo(a.a[2].x,a.a[2].y);c.lineTo(a.a[3].x,a.a[3].y);c.lineTo(a.a[4].x,a.a[4].y);c.lineTo(a.a[5].x,a.a[5].y);c.lineTo(a.a[0].x,a.a[0].y);c.strokeStyle=f.q;c.lineWidth=2;c.stroke()}function j(c,a,b){a.beginPath();a.moveTo(b.a[0].x,b.a[0].y);a.lineTo(b.a[1].x,b.a[1].y);a.lineTo(b.a[2].x,b.a[2].y);a.lineTo(b.a[3].x,b.a[3].y);a.lineTo(b.a[4].x,b.a[4].y);a.lineTo(b.a[5].x,b.a[5].y);a.lineTo(b.a[0].x,
b.a[0].y);a.fillStyle=f.D;a.fill();var h=!0,e=0,g=[-1,-1,-1,-1,-1,-1];a.lineWidth=b.lineWidth;for(var d=0;d<6;d++)if(h=!0,c.f[d]!=0){for(var i=1;i<4;i++){if(c.f[(d+i)%6]==c.f[d]){g[d]=(d+i)%6;h=!1;break}if(c.f[(6+d-i)%6]==c.f[d]){g[d]=(6+d-i)%6;h=!1;break}}h&&(g[d]=d)}a.save();a.rotate(r(60*c.orientation));a.rotate(r(120));for(d=0;d<6;d++){h=(d+c.orientation)%6;if(c.f[h]!=0)if(a.strokeStyle=f.r[c.f[h]],g[h]==h){var i=b.c[4].x*(4-e)/6,j=b.c[4].y*(4-1.5*e)/6;a.beginPath();a.moveTo(b.c[4].x,b.c[4].y);
a.lineTo(i,j);i=Math.sqrt(Math.pow(i,2)+Math.pow(j,2));a.moveTo(i,0);a.arc(0,0,i,0,Math.PI*1.5,!1);a.stroke();a.beginPath();a.strokeStyle=f.r[c.f[h]];a.arc(0,0,i,Math.PI,Math.PI*3,!1);a.stroke();a.beginPath();e++}else{if(g[(h+1)%6]==h||g[h]==(h+1)%6)a.save(),a.rotate(r(-60)),v(a,b.a[0].x,b.a[0].y,b.a[3].x+2,b.a[4].y),a.beginPath(),a.moveTo(b.c[5].x,b.c[5].y),a.quadraticCurveTo(0,0,b.c[0].x,b.c[0].y),a.stroke(),a.restore();if(g[(h+2)%6]==h||g[h]==(h+2)%6)a.save(),a.rotate(r(60)),v(a,b.c[1].x-b.b/4,
b.c[1].y,b.a[3].x,b.c[4].y),a.beginPath(),a.moveTo(b.c[3].x,b.c[3].y),a.quadraticCurveTo(0,0,b.c[5].x,b.c[5].y),a.stroke(),a.restore();if(g[(h+3)%6]==h||g[h]==(h+3)%6)a.save(),v(a,b.a[0].x,b.a[0].y-b.b/8,b.a[4].x,b.a[4].y),a.beginPath(),a.moveTo(b.c[4].x,b.c[4].y),a.quadraticCurveTo(0,0,b.c[1].x,b.c[1].y),a.stroke(),a.restore();if(g[(h+4)%6]==h||g[h]==(h+4)%6)a.save(),a.rotate(r(-60)),v(a,b.a[0].x,b.c[1].y,b.c[1].x+b.b/4,b.c[4].y),a.beginPath(),a.moveTo(b.c[5].x,b.c[5].y),a.quadraticCurveTo(0,0,b.c[3].x,
b.c[3].y),a.stroke(),a.restore();if(g[(h+5)%6]==h||g[h]==(h+5)%6)a.save(),a.rotate(r(60)),v(a,b.a[0].x,b.a[0].y-1,b.a[3].x,b.c[4].y),a.beginPath(),a.moveTo(b.c[3].x,b.c[3].y),a.quadraticCurveTo(0,0,b.c[2].x,b.c[2].y),a.stroke(),a.restore()}a.rotate(r(60))}a.restore()}function w(c,a,b){a||(a=0);c.save();c.translate(0,b.m);c.rotate(a);c.beginPath();c.moveTo(b.a[0].x,b.a[0].y);c.lineTo(b.a[1].x,b.a[1].y);c.lineTo(b.a[2].x,b.a[2].y);c.lineTo(b.a[3].x,b.a[3].y);c.lineTo(b.a[4].x,b.a[4].y);c.lineTo(b.a[5].x,
b.a[5].y);c.lineTo(b.a[0].x,b.a[0].y);c.fillStyle=f.s;c.fill();c.strokeStyle=f.q;c.stroke();c.restore()}function z(c,a){if(!n){n=!0;var b=l.d[m[0]][m[1]],h=c.getContext("2d"),e=a.b+b.i*(3*a.b/2),f=x(b.i,b.l,a);if(!isNaN(o)){h.save();h.translate(a.j,a.k);h.beginPath();h.save();v(h,e-a.b*1.5,f-a.b*1.5,e+a.b*1.5,f+a.b*1.5);h.fillRect(e-a.b,f-a.b-a.m,a.b*2,a.b*2+a.m);for(e=0;e<6;e++)if(b.e[e]){h.save();var f=b.e[e].i,g=b.e[e].l;h.translate(a.b+a.h*3*f+0.5,a.g*(2*g+1-f)+0.5);w(h,0,a);h.restore()}h.restore();
for(e=0;e<6;e++)if(b.e[e])h.save(),f=b.e[e].i,g=b.e[e].l,h.translate(a.b+a.h*3*f+0.5,a.g*(2*g+1-f)+0.5),j(b.e[e],h,a),s(h,a),h.restore();f=b.i;g=b.l;h.save();h.translate(a.b+a.h*3*f+0.5,a.g*(2*g+1-f)+0.5);h.translate(0,-1*a.m);w(h,o,a);h.rotate(o);j(b,h,a);s(h,a);h.restore();h.restore();n=!1}}}var M=this,e={},m,o=0,l={};f.r=f.lineColor;f.background=f.background;f.D=f.tileBackground;f.q=f.edge;f.s=f.bevel;var t=0,y=0,F=0,u,n=!1,p={p:!1,v:function(c){var a;a:{a=c.layerX;c=c.layerY;a-=e.j;c-=e.k;var b=
a*2/(3*e.b),f=b|0,d=b-1/3|0,b=c+e.height/(3*e.b)*a;b-=e.height/6;b/=e.height;var i=b|0,b=b-1/3|0;if(!(b<0||d<0||d>=l.d.length||b>=l.d[d].length)){if(b==i&&d==f){a=[d,b];break a}for(;d<=f;d++)for(var j=b;j<=i;j++)if(Math.sqrt(Math.pow(a-(e.b+d*(3*e.b/2)),2)+Math.pow(c-x(d,j,e),2))<e.height/2&&d<l.d.length&&j<l.d[d].length&&d>=0&&j>=0){a=[d,j];break a}}a=void 0}a&&l.d[a[0]]&&l.d[a[0]][a[1]]&&(m=a,u=[e.b+a[0]*(3*e.b/2)+e.j,x(a[0],a[1],e)+e.k],z($(g)[0],e))},w:function(c){if(u){var a=u[0]-c.layerX,c=
u[1]-c.layerY;p.p?o=-1*Math.atan2(a,c)+p.C:Math.abs(a)<e.b/2.5&&Math.abs(c)<e.b/2.5?o=0:(p.C=Math.atan2(a,c),p.p=!0)}},z:function(){p.p=!1;u=void 0;A(l.d[m[0]][m[1]],Math.round(o*6/(Math.PI*2))%6)}};this.complete=function(c){this.t=c};this.newpuzzle=this.u=function(c,a,b){B=!1;l={};l=C(c,a,b);this.o()};this.prepicon=this.A=function(){l.d[0][0].f=[0,1,2,1,2,2];D(t*0.45,e);e.j=t-e.h*(3*l.d.length+1);e.j/=2;e.j=Math.floor(e.j);e.k=y-e.g*l.d[0].length*2-e.m;e.k/=2;e.k=Math.floor(e.k);m=[0,0];o=Math.PI*
15/180;$(g).unbind("mouseup",this.n).unbind("mousemove",this.n).unbind("mousedown",this.n);z($(g)[0],e)};var I=0,B=!1;this.n=function(c){if(B)return!1;if(!c.layerX)c.layerX=c.clientX,c.layerY=c.clientY;if(c.type=="mousemove"){if(!m)return;p.w(c);(new Date).getTime()-I>=20&&(z($(g)[0],e),I=(new Date).getTime())}else if(c.type=="mousedown")F=(new Date).getTime(),p.v(c);else if(c.type=="mouseup"){if(!m)return;(new Date).getTime()-F<200?A(l.d[m[0]][m[1]],1):p.z(c);var a=l.d[m[0]][m[1]];o=0;m=void 0;if(!n){n=
!0;var c=[a.e[E],a.e[G],a.e[H],a,a.e[J],a.e[K],a.e[L]],b=g.getContext("2d");b.fillStyle=f.background;var h=e.b+a.i*(3*e.b/2),a=x(a.i,a.l,e);b.save();b.translate(e.j,e.k);b.save();v(b,h-e.b*1.5,a-e.b*1.5,h+e.b*1.5,a+e.b*1.5);b.fillRect(h-e.b*1.5,a-e.b*1.5,e.b*3,e.b*3);for(h=0;h<7;h++)c[h]&&(b.save(),b.translate(e.b+e.h*3*c[h].i+0.5,e.g*(2*c[h].l+1-c[h].i)+0.5),w(b,0,e),b.restore());b.restore();for(h=0;h<c.length;h++)if(c[h]){var a=c[h],d=e,i=void 0,i=g.getContext("2d");i.save();i.translate(d.b+d.h*
3*a.i+0.5,d.g*(2*a.l+1-a.i)+0.5);j(a,i,d);s(i,d);i.restore()}b.restore();n=!1}a:{for(c=0;c<l.d.length;c++)for(b=0;b<l.d[c].length;b++)if(!N(l.d[c][b])){c=!1;break a}c=!0}c&&(B=!0,M.t())}return!1};this.do_size=this.o=function(){var c=$(g),a=c.width(),c=c.height();t=a;y=c;D(Math.min(a*2/(3*l.d.length+3),c/(2*l.d[0].length+1+Math.sin(Math.PI/3))/Math.sin(2*Math.PI/6)),e);e.j=t-e.h*(3*l.d.length+1);e.j/=2;e.k=y-e.g*(l.d[0].length*2+1)-e.m;e.k/=2;a=l;if(!n){n=!0;c=g.getContext("2d");c.fillStyle=f.background;
c.fillRect(0,0,t+1,y+1);for(var b=0;b<a.d.length;b++)for(var d=0;d<a.d[b].length;d++)c.save(),c.translate(e.j,e.k),a.d[b][d]&&(c.translate(e.b+e.h*3*b+0.5,e.g*(2*d+1-b)+0.5),w(c,0,e)),c.restore();for(b=0;b<a.d.length;b++)for(d=0;d<a.d[b].length;d++)c.save(),c.translate(e.j,e.k),a.d[b][d]&&(c.translate(e.b+e.h*3*b+0.5,e.g*(2*d+1-b)+0.5),j(a.d[b][d],c,e),s(c,e)),c.restore();n=!1}};l=C(k,i,d);$(g).mouseup(this.n).mousemove(this.n).mousedown(this.n);this.o()}q.prototype.B=function(){this.o()};
q.redo_size=q.prototype.B;var E=0,G=1,H=2,L=3,K=4,J=5;function D(g,f){f.b=g;f.lineWidth=g*0.15;f.g=f.b*Math.sin(2*Math.PI/6);f.h=f.b/2;f.width=f.b*2;f.height=f.g*2;f.a={0:{x:-1*f.b,y:0},1:{x:-1*f.h,y:-1*f.g},2:{x:f.h,y:-1*f.g},3:{x:f.b,y:0},4:{x:f.h,y:f.g},5:{x:-1*f.h,y:f.g}};f.c={};for(var k=0;k<6;k++)f.c[k]={x:(f.a[k].x+f.a[(k+1)%6].x)/2,y:(f.a[k].y+f.a[(k+1)%6].y)/2};f.m=Math.min(5,f.height*0.1)}var O={0:[0,1],1:[0,0,1,1,2,2],2:[0,1,1,1,2,2,2,2]};
function C(g,f,k){for(var i=[],k=O[k],d=0;d<g;d++){i[d]=[];for(var s=Math.floor((d+1)/2)+f,j=Math.floor((d+1)/2);j<s;j++)i[d][j]={},i[d][j].f=[0,0,0,0,0,0],i[d][j].e=[],i[d][j].orientation=0,i[d][j].i=d,i[d][j].l=j}for(d=0;d<i.length;d++)for(j=0;j<i[d].length;j++)if(g=i[d][j])j!=0&&i[d][j-1]&&(g.e[G]=i[d][j-1],g.e[G].e[K]=g),d!=0&&i[d-1].length>j&&i[d-1][j]&&(g.e[J]=i[d-1][j],g.e[J].e[H]=g),d!=0&&j!=0&&i[d-1].length>j-1&&i[d-1][j-1]&&(g.e[E]=i[d-1][j-1],g.e[E].e[L]=g);for(d=0;d<i.length;d++)for(g=
0;g<i[d].length;g++)if(i[d][g])for(j=3;j<6;j++)i[d][g].e[j]&&(f=Math.floor(Math.random()*k.length),i[d][g].f[j]=k[f],i[d][g].e[j].f[(j+3)%6]=k[f]);for(d=0;d<i.length;d++)for(j=0;j<i[d].length;j++)i[d][j]&&A(i[d][j],Math.floor(Math.random()*6)%6);return{d:i}}function N(g){if(!g)return!0;for(var f=0;f<6;f++)if(g.e[f]){if(g.f[f]!=g.e[f].f[(f+3)%6])return!1}else if(g.f[f]>0)return!1;return!0}
function A(g,f){for(var k=[],i=0;i<6;i++)k[i]=g.f[i];f%=6;f=6-f;f%=6;for(i=0;i<6;i++)g.f[i]=k[(i+f)%6];g.orientation-=f;g.orientation+=6;g.orientation%=6}function r(g){return g/180*Math.PI}function v(g,f,k,i,d){g.beginPath();g.rect(f,k,i-f,d-k);g.clip()}function x(g,f,k){return k.height/2+f*k.height-k.height/2*g}window.Curvy=q;